-- ==============================================================================
-- SAMPLE PRODUCT DATA - E-COMMERCE STORE
-- ==============================================================================
-- Populates the store with realistic products across multiple categories
-- ==============================================================================

-- ==============================================================================
-- ELECTRONICS (15 Products)
-- ==============================================================================

INSERT INTO public.products (category_id, name, slug, description, short_description, image_url, mrp, price, cashback_amount, stock_quantity, is_featured, tags) VALUES

-- Get category ID for Electronics
((SELECT id FROM public.product_categories WHERE slug = 'electronics'),
'Apple iPhone 15 Pro Max (256GB)',
'iphone-15-pro-max-256gb',
'Experience the pinnacle of smartphone technology with the iPhone 15 Pro Max. Featuring the powerful A17 Pro chip, ProMotion display, and advanced camera system with 5x optical zoom.',
'Latest iPhone with A17 Pro chip and titanium design',
'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=800',
139900, 124900, 6245, 50, true,
ARRAY['smartphone', 'apple', 'premium', 'flagship']),

((SELECT id FROM public.product_categories WHERE slug = 'electronics'),
'Samsung Galaxy S24 Ultra (512GB)',
'samsung-s24-ultra-512gb',
'The ultimate Android flagship with S Pen, 200MP camera, and AI-powered features. Stunning 6.8" Dynamic AMOLED display.',
'Premium Android flagship with S Pen',
'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=800',
129900, 114900, 5745, 45, true,
ARRAY['smartphone', 'samsung', 'android', 'flagship']),

((SELECT id FROM public.product_categories WHERE slug = 'electronics'),
'Sony WH-1000XM5 Wireless Headphones',
'sony-wh1000xm5-headphones',
'Industry-leading noise cancellation with crystal-clear audio. 30-hour battery life and premium comfort for all-day listening.',
'Premium noise-canceling headphones',
'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800',
34990, 29990, 1499, 100, true,
ARRAY['headphones', 'sony', 'wireless', 'noise-canceling']),

((SELECT id FROM public.product_categories WHERE slug = 'electronics'),
'Apple MacBook Air M3 (13-inch, 256GB)',
'macbook-air-m3-256gb',
'Incredibly thin and light laptop powered by the M3 chip. Up to 18 hours of battery life with stunning Liquid Retina display.',
'Ultra-portable laptop with M3 chip',
'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=800',
119900, 109900, 5495, 30, true,
ARRAY['laptop', 'apple', 'macbook', 'ultrabook']),

((SELECT id FROM public.product_categories WHERE slug = 'electronics'),
'Dell XPS 15 (Intel i7, 16GB RAM, 512GB SSD)',
'dell-xps-15-i7-16gb',
'Premium Windows laptop with stunning InfinityEdge display, powerful performance, and sleek design.',
'High-performance Windows laptop',
'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=800',
149900, 134900, 6745, 25, false,
ARRAY['laptop', 'dell', 'windows', 'premium']),

((SELECT id FROM public.product_categories WHERE slug = 'electronics'),
'iPad Pro 12.9" M2 (256GB, Wi-Fi)',
'ipad-pro-129-m2-256gb',
'The ultimate iPad experience with M2 chip, Liquid Retina XDR display, and Apple Pencil support.',
'Professional-grade tablet',
'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=800',
109900, 99900, 4995, 40, false,
ARRAY['tablet', 'apple', 'ipad', 'professional']),

((SELECT id FROM public.product_categories WHERE slug = 'electronics'),
'Apple Watch Series 9 (45mm GPS)',
'apple-watch-series-9-45mm',
'Advanced health and fitness tracking with always-on Retina display. Track workouts, monitor heart health, and stay connected.',
'Smart fitness watch',
'https://images.unsplash.com/photo-1434493789847-2f02dc6ca35d?w=800',
44900, 39900, 1995, 60, false,
ARRAY['smartwatch', 'apple', 'fitness', 'health']),

((SELECT id FROM public.product_categories WHERE slug = 'electronics'),
'Canon EOS R6 Mark II (Body Only)',
'canon-eos-r6-mark-ii',
'Professional mirrorless camera with 24.2MP full-frame sensor, 40fps burst shooting, and advanced autofocus.',
'Professional mirrorless camera',
'https://images.unsplash.com/photo-1606980707146-b3a0c8f0e3e1?w=800',
249900, 229900, 11495, 15, false,
ARRAY['camera', 'canon', 'mirrorless', 'professional']),

((SELECT id FROM public.product_categories WHERE slug = 'electronics'),
'Samsung 55" QLED 4K Smart TV',
'samsung-55-qled-4k-tv',
'Stunning Quantum Dot technology with 4K resolution, HDR10+, and smart features powered by Tizen OS.',
'Premium 4K QLED TV',
'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=800',
89900, 74900, 3745, 20, false,
ARRAY['tv', 'samsung', '4k', 'smart-tv']),

((SELECT id FROM public.product_categories WHERE slug = 'electronics'),
'Bose SoundLink Revolve+ Bluetooth Speaker',
'bose-soundlink-revolve-plus',
'360-degree sound with deep bass. Water-resistant design with 16-hour battery life.',
'Portable Bluetooth speaker',
'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800',
24900, 19900, 995, 75, false,
ARRAY['speaker', 'bose', 'bluetooth', 'portable']),

((SELECT id FROM public.product_categories WHERE slug = 'electronics'),
'Logitech MX Master 3S Wireless Mouse',
'logitech-mx-master-3s',
'Ergonomic wireless mouse with ultra-fast scrolling, customizable buttons, and multi-device connectivity.',
'Premium wireless mouse',
'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800',
8990, 7490, 374, 150, false,
ARRAY['mouse', 'logitech', 'wireless', 'ergonomic']),

((SELECT id FROM public.product_categories WHERE slug = 'electronics'),
'Kindle Paperwhite (16GB)',
'kindle-paperwhite-16gb',
'Glare-free display that reads like real paper. Waterproof design with weeks of battery life.',
'E-reader with glare-free display',
'https://images.unsplash.com/photo-1592496431122-2349e0fbc666?w=800',
14999, 12999, 649, 100, false,
ARRAY['e-reader', 'kindle', 'amazon', 'books']),

((SELECT id FROM public.product_categories WHERE slug = 'electronics'),
'GoPro HERO12 Black',
'gopro-hero12-black',
'Ultimate action camera with 5.3K60 video, HyperSmooth 6.0 stabilization, and waterproof design.',
'Professional action camera',
'https://images.unsplash.com/photo-1606941369323-d2b0e9c0c8f8?w=800',
44900, 39900, 1995, 35, false,
ARRAY['camera', 'gopro', 'action-camera', 'waterproof']),

((SELECT id FROM public.product_categories WHERE slug = 'electronics'),
'Dyson V15 Detect Cordless Vacuum',
'dyson-v15-detect-vacuum',
'Intelligent cordless vacuum with laser detection and LCD screen showing particle count.',
'Smart cordless vacuum cleaner',
'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=800',
64900, 57900, 2895, 25, false,
ARRAY['vacuum', 'dyson', 'cordless', 'smart-home']),

((SELECT id FROM public.product_categories WHERE slug = 'electronics'),
'Anker PowerCore 20000mAh Power Bank',
'anker-powercore-20000mah',
'High-capacity portable charger with fast charging support for multiple devices.',
'High-capacity power bank',
'https://images.unsplash.com/photo-1609091839311-d5365f9ff1c5?w=800',
3999, 2999, 149, 200, false,
ARRAY['power-bank', 'anker', 'portable-charger', 'accessories']);

-- ==============================================================================
-- FASHION (12 Products)
-- ==============================================================================

INSERT INTO public.products (category_id, name, slug, description, short_description, image_url, mrp, price, cashback_amount, stock_quantity, is_featured, tags) VALUES

((SELECT id FROM public.product_categories WHERE slug = 'fashion'),
'Levi''s 511 Slim Fit Jeans - Dark Blue',
'levis-511-slim-fit-jeans',
'Classic slim fit jeans with stretch comfort. Timeless dark blue wash perfect for any occasion.',
'Premium slim fit denim jeans',
'https://images.unsplash.com/photo-1542272604-787c3835535d?w=800',
4999, 3499, 174, 100, true,
ARRAY['jeans', 'levis', 'denim', 'mens-fashion']),

((SELECT id FROM public.product_categories WHERE slug = 'fashion'),
'Nike Air Force 1 ''07 - White',
'nike-air-force-1-white',
'Iconic basketball-inspired sneakers with premium leather and Air cushioning.',
'Classic white sneakers',
'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800',
8995, 7495, 374, 80, true,
ARRAY['sneakers', 'nike', 'shoes', 'casual']),

((SELECT id FROM public.product_categories WHERE slug = 'fashion'),
'Zara Oversized Blazer - Black',
'zara-oversized-blazer-black',
'Sophisticated oversized blazer with structured shoulders. Perfect for office or evening wear.',
'Premium oversized blazer',
'https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800',
5999, 4499, 224, 60, false,
ARRAY['blazer', 'zara', 'formal', 'womens-fashion']),

((SELECT id FROM public.product_categories WHERE slug = 'fashion'),
'Adidas Originals Trefoil Hoodie',
'adidas-trefoil-hoodie',
'Comfortable cotton-blend hoodie with iconic Trefoil logo. Perfect for casual everyday wear.',
'Classic Adidas hoodie',
'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800',
3999, 2999, 149, 120, false,
ARRAY['hoodie', 'adidas', 'streetwear', 'casual']),

((SELECT id FROM public.product_categories WHERE slug = 'fashion'),
'Ray-Ban Aviator Classic Sunglasses',
'rayban-aviator-classic',
'Timeless aviator sunglasses with UV protection and metal frame.',
'Iconic aviator sunglasses',
'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800',
12990, 9990, 499, 90, false,
ARRAY['sunglasses', 'rayban', 'accessories', 'eyewear']),

((SELECT id FROM public.product_categories WHERE slug = 'fashion'),
'H&M Slim Fit Cotton Shirt - White',
'hm-slim-fit-shirt-white',
'Classic white cotton shirt with slim fit. Essential wardrobe staple.',
'Premium cotton dress shirt',
'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800',
1999, 1499, 74, 150, false,
ARRAY['shirt', 'hm', 'formal', 'cotton']),

((SELECT id FROM public.product_categories WHERE slug = 'fashion'),
'Fossil Gen 6 Leather Watch - Brown',
'fossil-gen6-leather-watch',
'Elegant analog watch with genuine leather strap and stainless steel case.',
'Classic leather watch',
'https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=800',
14995, 11995, 599, 45, false,
ARRAY['watch', 'fossil', 'accessories', 'leather']),

((SELECT id FROM public.product_categories WHERE slug = 'fashion'),
'Puma Running Shorts - Black',
'puma-running-shorts-black',
'Lightweight performance shorts with moisture-wicking fabric and zippered pockets.',
'Athletic running shorts',
'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=800',
1999, 1299, 64, 100, false,
ARRAY['shorts', 'puma', 'activewear', 'running']),

((SELECT id FROM public.product_categories WHERE slug = 'fashion'),
'Tommy Hilfiger Polo T-Shirt - Navy',
'tommy-hilfiger-polo-navy',
'Classic polo shirt with signature flag logo. Premium cotton piqué fabric.',
'Premium polo shirt',
'https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?w=800',
3499, 2499, 124, 110, false,
ARRAY['polo', 'tommy-hilfiger', 'casual', 'cotton']),

((SELECT id FROM public.product_categories WHERE slug = 'fashion'),
'Lululemon Align Leggings - Black',
'lululemon-align-leggings',
'Buttery-soft high-rise leggings perfect for yoga and everyday wear.',
'Premium yoga leggings',
'https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=800',
9800, 7800, 390, 70, false,
ARRAY['leggings', 'lululemon', 'yoga', 'activewear']),

((SELECT id FROM public.product_categories WHERE slug = 'fashion'),
'Michael Kors Jet Set Tote Bag',
'michael-kors-jetset-tote',
'Spacious leather tote bag with signature MK logo. Perfect for work or travel.',
'Designer leather tote bag',
'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800',
24900, 19900, 995, 30, true,
ARRAY['bag', 'michael-kors', 'leather', 'luxury']),

((SELECT id FROM public.product_categories WHERE slug = 'fashion'),
'Calvin Klein Cotton Boxer Briefs (3-Pack)',
'calvin-klein-boxer-briefs-3pack',
'Comfortable cotton-stretch boxer briefs with iconic waistband. Pack of 3.',
'Premium boxer briefs set',
'https://images.unsplash.com/photo-1489987707025-afc232f7ea0f?w=800',
2999, 1999, 99, 200, false,
ARRAY['underwear', 'calvin-klein', 'essentials', 'cotton']);

-- Continue with other categories in next section...

