// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Hardcoded for stability
// Fallbacks for local stability if .env fails to load correctly
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://vwzqmjhcfetjzhmyjtkr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3enFtamhjZmV0ZnpobXlqdGtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgxNjIzMTEsImV4cCI6MjA1MzczODMxMX0.g3E_l1tH-XQ9CqD2iC8Ea3SpuMDTHZveqZNHaJHMY3M";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);